/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#b9cacb',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#849495',
        'outline-variant': '#3b494b',
        'surface-tint': '#00dbe9',
        primary: '#dbfcff',
        'on-primary': '#00363a',
        'primary-container': '#00f0ff',
        'on-primary-container': '#006970',
        'inverse-primary': '#006970',
        secondary: '#c8c6c5',
        'on-secondary': '#313030',
        'secondary-container': '#474746',
        'on-secondary-container': '#b7b5b4',
        tertiary: '#f8f5f5',
        'on-tertiary': '#303030',
        'tertiary-container': '#dbd9d8',
        'on-tertiary-container': '#5f5e5e',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#7df4ff',
        'primary-fixed-dim': '#00dbe9',
        'on-primary-fixed': '#002022',
        'on-primary-fixed-variant': '#004f54',
        'secondary-fixed': '#e5e2e1',
        'secondary-fixed-dim': '#c8c6c5',
        'on-secondary-fixed': '#1c1b1b',
        'on-secondary-fixed-variant': '#474746',
        'tertiary-fixed': '#e4e2e1',
        'tertiary-fixed-dim': '#c8c6c6',
        'on-tertiary-fixed': '#1b1c1c',
        'on-tertiary-fixed-variant': '#474747',
        background: '#131313',
        'on-background': '#e5e2e1',
        'surface-variant': '#353534',
      },
      fontFamily: {
        geist: ['Geist', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.04em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '1.6', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', letterSpacing: '0em', fontWeight: '400' }],
        'mono-label': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0px',
        none: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        '3xl': '0px',
        full: '9999px',
      },
      spacing: {
        'sidebar-width': '260px',
        gutter: '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
}
